// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBelpXQJTjCQLDFh2_Sws6TxH8r_7uC4V0',
    appId: '1:294685297051:web:0cdcfb4722b8e342e4b93e',
    messagingSenderId: '294685297051',
    projectId: 'uni-project-180cd',
    authDomain: 'uni-project-180cd.firebaseapp.com',
    storageBucket: 'uni-project-180cd.appspot.com',
    measurementId: 'G-5RJQ9G4110',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc1uiEkAniIkvzmQeaJrIE2qIk24TiN_c',
    appId: '1:294685297051:android:6196c37ed11b98dbe4b93e',
    messagingSenderId: '294685297051',
    projectId: 'uni-project-180cd',
    storageBucket: 'uni-project-180cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEqzM17U9t6WdDe8XQH4yqEO2vy46jfXY',
    appId: '1:294685297051:ios:efe015600ba03fdfe4b93e',
    messagingSenderId: '294685297051',
    projectId: 'uni-project-180cd',
    storageBucket: 'uni-project-180cd.appspot.com',
    iosClientId: '294685297051-39j1k7khf322sl4etm8i1l44653ob7ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEqzM17U9t6WdDe8XQH4yqEO2vy46jfXY',
    appId: '1:294685297051:ios:1790d3a6f7cb8deae4b93e',
    messagingSenderId: '294685297051',
    projectId: 'uni-project-180cd',
    storageBucket: 'uni-project-180cd.appspot.com',
    iosClientId: '294685297051-uknkfs27h0o56tbkau9oit930ar72p6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniproject.RunnerTests',
  );
}
